== Al Lector

Te pido que seas serio cuando tomes en tu mano este tratado y te propongas leerlo,
y que lo único que tengas en mente sea el estado de tu alma inmortal;
y que dejes que tu espíritu se incline a la
"`medida del Espíritu de Dios dada a ti para provecho,`"^
footnote:[1 Corintios 12:7]
para que por ella el ojo de tu entendimiento sea
abierto y puedas ver las cosas escritas aquí,
que son para tu propio bienestar eterno.
Y no dejes que tus propios pensamientos e imaginaciones,
en la sabiduría que es de abajo (la cual es animal y terrenal) sean el juez aquí;
sino permanece quieto, fuera de tus propias comprensiones;
y pon tu mirada de manera verdadera y diligente en
la Palabra que está en tu corazón y en tu boca,
puesta ahí para que la obedezcas y la cumplas.
De este modo,
tu corazón estará verdaderamente abierto para leer con deleite
las cosas reveladas por el Espíritu de la Verdad,
que todo lo escudriña, aun lo profundo de Dios; y así mi ruego en el espíritu,
que es que los ojos de los ciegos sean abiertos, y los oídos de los sordos destapados,
será contestado; y el Señor Dios Todopoderoso tendrá el honor de Su propia obra,
y tú recibirás beneficio de ella;
lo cual es el deseo y anhelo de uno que trabaja por la salvación perfecta de Sion.

[.signed-section-signature]
Charles Marshall

[.signed-section-context-close]
Bristol, el día segundo del Séptimo mes, en el año 1673
