== El Estado de Felicidad del Hombre antes de la Caída

En el principio creó Dios los cielos y la tierra;
y después de haber hecho todas las cosas sobre la tierra, hizo al hombre a Su imagen,
lo formó del polvo de la tierra, y sopló en él el aliento de vida,
y fue el hombre un alma viviente.
Y el Señor plantó un huerto en Edén, y puso allí al hombre que había formado;
e hizo nacer de la tierra todo árbol delicioso a la vista, y bueno para comer;
también el árbol de la vida en medio del huerto,
y el árbol del conocimiento del bien y el mal.
Y Aquel que hizo al hombre y lo puso en este estado,
le dio una ley para preservarlo en él, como testifican las Escrituras de la Verdad,
diciendo: "`Y mandó el Señor Dios al hombre, diciendo:
De todo árbol del huerto libremente podrás comer;
pero del árbol del conocimiento del bien y el mal no comerás;
porque el día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:16-17]
Y vio Dios todo lo que había hecho, y he aquí que era bueno en gran manera;
el árbol del conocimiento del bien y el mal era bueno, pero no para comer.

El hombre fue dotado con sabiduría Divina,
de modo que cuando el Señor Dios le trajo a Adán
toda bestia del campo y toda ave de los cielos,
él les puso nombre; y de la manera que Adán llamó a los animales vivientes,
ese era su nombre.
El hombre, en su estado original, era la imagen de Dios, un alma viviente,
una planta noble, una semilla completamente recta, lleno de sabiduría y virtud Divina,
vestido de inocencia y gloria, adornado con belleza celestial,
disfrutando continuamente del amor y favor de Dios,
teniendo su comunión diaria con Aquel que lo había hecho.
No había muerte, ni oscuridad, ni dolor, ni razones para llorar, ni transgresión,
ni conocimiento del mal, porque él moraba en la vida inocente, y fue puesto en el huerto,
al cual entraba el río que salía del Edén para regarlo.
¡Oh, que estado tan bienaventurado! ¡Oh, que condición tan feliz! ¡Oh,
que inexpresable disfrute, belleza y gloria!
No es posible que la lengua del hombre exprese completamente
ese estado bendito y feliz de gozo,
paz, santidad, justicia y plenitud de vida,
en el cual el hombre estaba antes de transgredir la ley real de Dios.
