[short="El Estado del Hombre En la Caída"]
== El Estado Miserable del Hombre En la Caída

Pero aquel que no guardó su primera morada, ni permaneció en la Verdad,
envidiaba la felicidad que el hombre tenía en la Verdad, y, por lo tanto,
como una serpiente,
más astuta que todos los animales del campo que el Señor Dios había hecho,
vino a la mujer y le dijo: "`¿Conque Dios os ha dicho:
'`No comáis de todo árbol del huerto`'?`" La mujer respondió:
"`Del fruto de los árboles del huerto podemos comer;
pero del fruto del árbol que está en medio del huerto dijo Dios: No comeréis de él,
ni le tocaréis, para que no muráis.`" Entonces la serpiente le dijo a la mujer:
"`No moriréis; sino que sabe Dios que el día que comáis de él,
serán abiertos vuestros ojos, y seréis como Dios,
sabiendo el bien y el mal;`" y aquí la serpiente obtuvo una entrada.
Cuando la mujer vio que el árbol era bueno para comer, y que era agradable a los ojos,
y árbol codiciable para alcanzar la sabiduría; ella tomó de su fruto, y comió;
y dio también a su marido, el cual comió, así como ella,
y fueron abiertos los ojos de ambos.

Aquí prevaleció el dios de este mundo,
logrando abrir un ojo que veía el mal como algo agradable,
y cegando el verdadero ojo en estos hijos de desobediencia,
para que no pudieran contemplar más la gloria de Dios.
Y aquí ellos perdieron el manto de justicia y el vestido de inocencia.
Entonces ellos oyeron la voz del Señor Dios que se paseaba en el huerto al aire del día,
y Adán y su esposa se escondieron de la presencia del Señor Dios.
Y llamó el Señor Dios a Adán, y le dijo: "`¿Dónde estás tú?`" Y el hombre respondió:
"`Oí tu voz en el huerto, y tuve miedo, porque estaba desnudo;
y me escondí.`" Y dijo el Señor Dios: "`¿Quién te enseñó que estabas desnudo?
¿Has comido del árbol de que yo te mandé no comieses?`"
Él comenzó a excusarse, diciendo: "`La mujer que me diste por compañera me dio del árbol,
y yo comí.`" Entonces el Señor Dios dijo a la mujer: "`¿Qué es lo que has hecho?`"
Y dijo la mujer: "`La serpiente me engañó, y comí.`" Y el Señor Dios dijo a la serpiente:
"`Por cuanto esto hiciste,
maldita serás entre todas las bestias y entre todos los animales del campo;
sobre tu pecho andarás, y polvo comerás. Y pondré enemistad entre ti y la mujer,
y entre tu simiente y la Simiente suya; ésta te herirá en la cabeza,
y tú Le herirás en el calcañar.`" Entonces el Señor sacó al hombre del huerto,
para que labrase la tierra,
y puso al oriente del huerto de Edén querubines y una espada encendida,
que se revolvía por todos lados, para guardar el camino del árbol de la vida.

¡Oh, que cambio tan triste! ¡Oh,
que condición tan lamentable y desecha! ¡Que caída tan grande!
Aquel que estaba hecho a la imagen del Ser incorruptible, siendo un alma viviente,
que moraba en el huerto del Señor, donde estaba el árbol de la vida,
y donde la gloria del Ser Divino era experimentada y disfrutada,
ahora fue sacado de todo esto y llevado a la tierra; ¡y no sólo eso,
sino que fueron puestos los querubines y la espada encendida,
que se revolvía por todos lados, para guardar el camino del árbol de la vida! ¡Espantaos,
oh cielos, sobre esto, y horrorizaos oh tierra!
El Señor Dios crio hijos, y ellos se rebelaron contra Él.

Ahora bien, ¿cuál fue la causa y razón de este cambio,
que llevó al hombre a este estado y condición tan miserables?
¿Acaso no fue la desobediencia a la ley justa de Dios?
¿Acaso no entró el pecado al mundo por la desobediencia, y por el pecado la muerte?
¿Y no continúa el pecado en el mundo por la desobediencia?
¿Entra ahora el pecado de alguna manera diferente
a aquella por la que entró en ese entonces?
¿No sigue entrando por el pecado, la muerte que ha reinado,
y reina sobre todos los que están en el estado caído de Dios,
'`aun en los que no pecaron a la manera de la transgresión de Adán?`'^
footnote:[Romanos 5:14]
Porque no todos han pecado de la misma manera que él,
quien fue engañado con la expectativa de alcanzar un estado
mayor a ese en el que el Señor Dios lo había puesto.
Pero toda iniquidad, de cualquier tipo, brota de un mismo terreno,
y separa al hombre de su Dios.
Así que el terreno de toda iniquidad y transgresión es la
desobediencia del hombre a la ley justa de Dios,
cuya desobediencia produce muerte.

Pero ¿qué fue lo que murió en Adán? ¿Y qué significaba esta muerte?
Porque el Señor dijo: "`el día que comieres del árbol, ciertamente morirás;`" y,
sin embargo, aunque él comió, continuó viviendo externamente, y tuvo hijos.

Fue el hombre interior el que murió,
el cual había sido hecho por el aliento de vida del Altísimo.
Porque el hombre, al salir del consejo del Señor por su desobediencia,
fue separado de la vida de Dios,
y por lo tanto se hizo insensible de esa vida en
la que él era una semilla completamente recta,
y una planta noble.
En su degeneración él murió internamente.
Los sentidos internos del hombre interior se perdieron; el oído interno fue tapado;
el ojo interno fue cegado; el sentido interno para gustar cuán bueno es el Señor;
la capacidad interna de sentir Su virtud Divina (que es poder, vida, amor y gozo puros);
el sentido interno para olfatear, etc., todo esto se perdió. Y en lugar de esto,
fue abierto un oído que obedeció la voz del extraño;
y fue abierto un ojo que vio el fruto prohibido como algo agradable y codiciable;
los vestidos celestiales de inocencia, mansedumbre y rendición se perdieron;
y de este modo llegó a estar "`sin Dios en el mundo.`"^
footnote:[Efesios 2:12]
En este estado el hombre ya no tenía ninguna capacidad de morar en el huerto,
o de participar del árbol celestial de la vida que estaba en medio del mismo;
y en este estado están todos los hijos e hijas inconversos de los hombres,
independientemente de todas sus profesiones religiosas,
que no son más que cubiertas de hojas de higuera.

Pero a medida que la ley del Espíritu de vida se levante y se manifieste,
y los hijos e hijas de los hombres sean despertados por ella,
ellos tendrán una perspectiva y una verdadera consciencia de su estado y condición interior,
lo cual sin duda hará que se levante un clamor en sus almas: "`¡Oh,
que miserable mi estado! ¡Oh,
que espantosa mi condición!`" Es aquí cuando se ve cómo
el pecado ha entrado y ha traído la muerte con él;
porque la paga del pecado es muerte, la misma muerte que vino sobre Adán,
y sobre todos los que desde entonces han desobedecido la ley recta y espiritual de Dios,
que es justa, santa y buena.
Esta ley existía antes de la transgresión, y siempre lleva a Cristo,
la Simiente prometida, el don de Dios, que es vida eterna.

El hombre, habiéndose apartado así de esa naturaleza,
imagen y semilla en la que tenía su ser antes de la transgresión,
se volvió "`un sarmiento degenerado de una vid extraña`"^
footnote:[Jeremías 2:21 LBLA]
delante del Señor Dios.
Y de los hijos e hijas de los hombres (conforme ellos permanezcan unidos a esta
naturaleza y semilla de la serpiente que ha contaminado al hombre en alma,
cuerpo y espíritu) proceden las ramas y los frutos de la iniquidad.

Pero Dios, en su inmensa misericordia,
viendo que el hombre había caído en este estado miserable y lamentable,
ha abierto un camino por el cual puede ser restaurado a sí Mismo otra vez;
_cuyo camino es la Simiente prometida,_ acerca de la cual le dijo a la serpiente:
"`Pondré enemistad entre ti y la mujer, y entre tu simiente y la Simiente suya;
esta te herirá en la cabeza,
y tú Le herirás en el calcañar.`" Aquí la misericordia
de Dios fue extendida sobre la humanidad,
al darle la Simiente, que es Cristo Jesús; de lo contrario todos serían como Sodoma,
y semejantes a Gomorra, que Dios destruyó con fuego en Su ira.
Cristo es esa Simiente escogida sobre la que Él "`ha puesto el socorro,`"^
footnote:[Salmo 89:19]
quien es poderoso para salvar, el cual es la imagen del Dios invisible,
el primogénito de toda creación (en cuya imagen el hombre estaba antes de la transgresión),
quien estaba glorificado con el Padre antes que el mundo fuese.
Este es Aquel de quien doy testimonio,
declarando que Él es el camino de vida y salvación;
y que no hay otro nombre en que el hombre pueda ser salvo,
excepto por medio de Aquel que era, que es, y que ha de venir;
quien es desde la eternidad y hasta la eternidad, la Roca Eterna que seguía a Israel,
y que "`estuvo en la iglesia en el desierto,`"^
// lint-disable invalid-characters
footnote:[Hechos 7:38 RV 1602 Purificada (Gr. ἐκκλησία)]
como Esteban testificó antes que fuera apedreado.
Este es Aquel, que ni tiene principio de días, ni fin de vida;
quien se manifestó en el cumplimiento del tiempo,
no tomando para Sí la naturaleza de los ángeles,
sino que tomó la de la simiente de Abraham,^
footnote:[Hebreos 2:16 RV 1602 Purificada y RVG]
para quien había un cuerpo preparado para hacer la voluntad de Su Padre; quien, asimismo,
después de haberla cumplido, subió a donde estaba antes,
por encima de todos los cielos para llenarlo todo.
Este es el Emanuel, Dios con nosotros; Jesús, el Salvador; Cristo, el Ungido;
quien ha sido llamado por varios nombres; y ha sido mencionado con diferentes títulos,
a través de la boca de Sus siervos los profetas y
apóstoles en las eras y generaciones pasadas.
Este es el único Amado de los redimidos, y este es nuestro Amigo.

Y ahora Él, quien es el Anciano de días,
se ha levantado y se está levantando en el poder de Su fuerza,
(cuyas salidas son desde el principio, desde los días de la eternidad),
y está revelando el antiguo y buen camino y senda de vida, en la que caminaron Abel, Set,
Enoc, Noé, Abraham, Isaac, Jacob, y todos los siervos, profetas,
apóstoles y santos del Dios Altísimo en todas las eras y generaciones.
Este camino existía antes de todos los caminos y adoraciones que han sido
inventados y establecidos en la voluntad y tiempo del hombre;
porque todos los santos hombres del Dios Altísimo^
footnote:[Daniel 7:18, 22,25, 2 Pedro 1:21], adoraban a Dios en el Espíritu de santidad,
en el cual fueron aceptados por Aquel que es Dios de los espíritus de toda carne;
y ninguna forma de adoración externa jamás fue aceptable al Señor,
excepto cuando era realizada en este Espíritu.
