[#de-la-caida, short="Cómo Ser Restaurados de la Caída"]
== El Camino para Ser Restaurados de la Caída, a la Imagen de Dios, En la Cual Estaba el Hombre antes de la Caída.

Pero lo que en verdad siento fuertemente en mi espíritu declarar
(habiendo obtenido misericordia para ver el camino de vida y salvación
revelado y abierto) es cómo Él obra la salvación,
y cómo la humanidad puede ser traída de regreso a Él, quien es el Camino,
la Verdad y la Vida,
y ser sacada de debajo del poder y dominio de la semilla de la
serpiente (en la cual todos han sido por naturaleza hijos de ira).
Y no sólo eso,
sino que me es impuesta la necesidad de predicar el Evangelio de Cristo Jesús,
y de declarar el camino de vida y salvación a mis paisanos por toda esta isla de Inglaterra;
y ahora siento también una necesidad impuesta sobre mi espíritu
de dejar un testimonio escrito de esto.

Las personas generalmente reconocen que en el primer Adán todos mueren,
y que en el segundo Adán (Cristo, el Señor) todos son vivificados otra vez.
Pero _cómo_ la humanidad puede salir de este estado de muerte en el primer Adán,
y llegar a este estado de vida en el segundo Adán,
es lo que la sabiduría de este mundo nunca ha sabido ni comprendido correctamente.
El hombre, por medio de esta sabiduría,
sólo ha imaginado y concebido algo en la mente carnal respecto a este gran misterio,
y de este modo ha establecido muchas imaginaciones del camino
de vida y salvación. Y muchos han dicho "`helo aquí,
helo allí,`"^
footnote:[Lucas 17:21]
invitando a otros a los numerosos caminos inventados e imaginados que
el hombre ha establecido en su sabiduría caída. Pero el día ha amanecido,
y su luz está saliendo cada vez más (engrandecido y alabado sea el nombre del Dios Altísimo),
en el cual todos los caminos inventados,
establecidos en la voluntad y sabiduría del hombre (que es terrenal,
animal y diabólica) llegarán a su fin.
Y ahora, en el nombre del Dios Altísimo, todas las esculturas, obra de manos de hombres,
y la sabiduría terrenal serán hechas pedazos y molidas hasta ser reducidas a polvo;
la boca del Señor de los ejércitos lo ha hablado,
el cual lo hará con la fuerza de Su brazo.

Por lo tanto,
tiemblen todos ustedes fabricadores de imágenes de todas las denominaciones,
quienes han estado haciendo semejanzas del camino de vida
y salvación en su sabiduría caída y en sus voluntades corruptas,
y han hecho dioses de ellas, y se han arrodillado ante ellos y los han adorado;
de modo que puede decirse del cristianismo (así llamado)
lo mismo que una vez fue dicho de Israel:
"`Según el número de tus ciudades, oh, Judá, fueron tus dioses.`"^
footnote:[Jeremías 2:28, 11:13]

Pero ahora está llegando el cumplimiento del tiempo,
en el que el camino antiguo de santidad (por el cual caminaron los justos en
todas las edades y generaciones) es puesto delante y está siendo manifestado;
cuyo camino es Cristo Jesús,
el don del amor del Padre para con los hijos e hijas de los hombres,
quien ha sido (como fue mencionado anteriormente) declarado por
Sus profetas y apóstoles mediante varios nombres o títulos,
según le ha placido a Él manifestarse a ellos, y según Su Espíritu les daba que hablasen.
Entre muchos otros títulos,
Él ha sido declarado como Sacerdote para siempre según el orden de Melquisedec,
como la Roca que seguía a Israel, que estuvo en la iglesia en el desierto, como Rey,
Legislador, Admirable, Consejero, Príncipe de paz, Renuevo,
como Luz para revelación a los gentiles, el Brazo de Salvación de Dios, el Mesías,
como Pacto, Jefe, Maestro, Capitán, el Cuerno del Ungido de Dios,
como Piedra de tropiezo, un Fundamento puesto en Sion, la Piedra Angular;
la Palabra de Dios, la Palabra que era en el principio,
la Luz verdadera que alumbra a todo hombre que viene a este mundo, el Camino, la Verdad,
y la Vida, Rey de reyes, Señor de señores, Cristo; Emanuel, Jesús,
el Principio de la creación de Dios, el Primogénito de toda creación,
el Primogénito de entre los muertos, el Testigo Fiel, el Alfa y Omega,
la Estrella resplandeciente de la mañana, la imagen del Dios invisible,
el Linaje de David.
Se ha hablado de Él usando estos y otros nombres, y, aun así,
Él tiene un nombre el cual ninguno conoce sino Él mismo,
quien es esa única Fuente Eterna de Bendición, y el único y precioso Salvador;
y no hay otro fuera de Él.

Y ahora, por el poder del Dios santo y eterno, Él es predicado bajo el nombre de _Luz,_
en esta isla de los Gentiles, tal como fue profetizado antiguamente por Isaías,
quien dijo: "`Poco es para mí que Tú seas Mi siervo para levantar las tribus de Jacob,
y para que restaures el remanente de Israel; también te di por luz de las naciones,
para que seas Mi salvación hasta lo postrero de la tierra.`"^
footnote:[Isaías 49:6]
Y esto es lo mismo que Juan testificó, diciendo: "`En el principio era la Palabra,
y la Palabra era con Dios, y la Palabra era Dios.
El era en el principio con Dios.
Todas las cosas por Él fueron hechas; y sin Él nada de lo que es hecho, fue hecho.
En Él estaba la vida; _y la vida era la luz de los hombres._
Y la luz en las tinieblas resplandece; y las tinieblas no la comprendieron.`"
"`Hubo un hombre enviado de Dios, el cual se llamaba Juan.
Este vino por testimonio, para que diese testimonio de la luz,
a fin de que todos creyesen por Él. No era él la luz,
sino para que diese testimonio de la luz.
Aquella luz verdadera, que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:1-9 RVG, RV 1602 purificada, LBLA]
Y con esto concuerda el testimonio del justo Simeón,
quien movido por el Espíritu fue al templo, y tomó al niño Jesús en sus brazos, y dijo:
"`Ahora, Señor, despides a tu siervo en paz, conforme a tu palabra;
porque han visto mis ojos tu salvación,
la cual has preparado en presencia de todos los pueblos;
luz para revelación a los gentiles, y gloria de tu pueblo Israel.`"^
footnote:[Lucas 2:29-32]
Este es Aquel de quien damos testimonio, _cuya luz es el camino de vida:_
"`Y esta es la condenación: que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras son malas.
_Porque todo aquel que hace lo malo, aborrece la luz_ y no viene a la luz,
para que sus obras no sean reprendidas.
Mas el que practica la verdad viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.`"^
footnote:[Juan 3:19-21]

Ahora bien, esta luz, de la cual dan testimonio los siervos del Altísimo,
es lo mismo que ha sido declarado con diferentes nombres.
Porque esta manifestación de Dios en el hombre algunas veces es llamada la Palabra,
el Espíritu, la Ley, la Gracia de Dios; y la Palabra, Luz, Gracia,
Ley y Espíritu son todas una misma cosa en naturaleza, aunque tienen diversos nombres.
Moisés llamó a esta manifestación de Dios la Palabra,
y dirigió a los hombres a esta Palabra en el corazón y en la boca.^
footnote:[Deuteronomio 30:14, etc.]
Y Pablo, ese hombre iluminado, refiriéndose a esto, dice:
"`Pero la justicia que es por la fe dice así: No digas en tu corazón:
¿Quién subirá al cielo?
(esto es, para traer abajo a Cristo); o, ¿quién descenderá al abismo?
(esto es, para hacer subir a Cristo de entre los muertos).`"
Mas ¿qué dice?
"`Cerca de ti está la palabra,
en tu boca y en tu corazón. Esta es la Palabra de fe que predicamos.`"^
footnote:[Romanos 10:6-8]
Esta es la palabra profética más segura,
a la cual Pedro nos dice que debemos estar atentos,
como a una luz que alumbra en un lugar oscuro, hasta que el día esclarezca,
y el lucero de la mañana salga en el corazón.^
footnote:[2 Pedro 1:19]

Esta luz es la ley del Espíritu de vida, que Pablo conocía,
y que luchaba contra la ley del pecado y de la muerte en sus miembros.
Esta es la ley en el corazón, y el Espíritu en lo íntimo,
el nuevo pacto del Dios Altísimo.
Esta es la ley que convierte el alma,
en cuya ley Pablo se deleitaba (según el hombre interior) y de
la cual testifican abundantemente las Escrituras de la Verdad.
Esta es la gracia que "`trae salvación,`" como Pablo declaró,
la cual "`se ha manifestado a todos los hombres`" en diferentes medidas,
como el talento o mina de Dios,
enseñando a todos los que son conducidos y guiados por ella
"`a renunciar a toda impiedad y a los deseos mundanos;
y a vivir sobria, justa y piadosamente en este presente mundo.`"^
footnote:[Tito 2:11-12 RV 1960 y RV 1602 purificada]
Esta es esa gracia de la cual el Señor (el dador de ella) le dijo
a Pablo que era suficiente para librarlo de su tentación,
del aguijón en la carne.
El mismo apóstol le dijo a los Efesios, "`por gracia sois salvos,`"^
footnote:[Efesios 2:5, 8] etc.
Y esta es la "`manifestación del Espíritu dada a cada hombre para provecho.`"^
footnote:[1 Corintios 12:7]
Ella es ese buen Espíritu del Señor dado a Israel, "`contra el cual fueron rebeldes,`"^
footnote:[Salmos 106:33 LBLA; Isaías 63:10; Nehemías 9: 20-26]
así como lo fue el mundo antiguo, al cual el Señor le dijo:
"`No contenderá mi espíritu con el hombre para siempre.`"^
footnote:[Génesis 6:3]
Este Espíritu (Luz, Palabra,
o Gracia) es dado a la humanidad como su líder y guía para salir del pecado,
la muerte y la oscuridad, en lo cual el hombre cayó por desobedecer la ley justa de Dios,
como las Sagradas Escrituras testifican de manera clara y plena.

Pero en este punto,
hay una objeción que surge rápidamente en algunos
cuyo entendimiento todavía no ha sido abierto,
y cuya comprensión de la salvación se encuentra en esa sabiduría que es de abajo,
y en la voluntad y razonamiento de hombres que están degenerados de la vida de Dios.
Algunos de estos se han preguntado si predicar este Espíritu y gracia de Dios,
que se manifiesta en el interior,
tiende a invalidar la aparición de Cristo Jesús en la carne, y Sus sufrimientos, muerte,
resurrección y ascensión. A esto respondo: No;
porque ninguno jamás ha discernido o disfrutado verdaderamente
el beneficio de la manifestación de Cristo Jesús en la carne,
salvo en la medida en que su corazón haya sido abierto,
y su entendimiento haya sido iluminado por la luz;
que es una medida de la plenitud Divina que habita en Él. Y esta luz es
impartida al alma inmortal como el amor universal de Dios (manifestado
en el Hijo de Su Amor) para con todas las familias de la tierra,
como eso que revela y descubre la voluntad de Aquel de cuya plenitud Divina ella procede.
De esto las Escrituras testifican, diciendo:
"`Porque ¿quién de los hombres sabe las cosas del hombre,
sino el espíritu del hombre que está en él? Así tampoco nadie conoció las cosas de Dios,
sino el Espíritu de Dios.`"^
footnote:[1 Corintios 2:11]

Los corazones de los judíos, al no estar sazonados con esta gracia de Dios,
ni conocer el don de Dios (que es vida eterna), no discernieron, ni amaron,
ni recibieron a Cristo Jesús cuando Él se manifestó en ese cuerpo externo.
Aunque decían que honraban y veneraban a los profetas,
y vivían con la expectativa de que se cumplieran
muchas profecías acerca de la venida del Mesías,
cuando Él, a Su debido tiempo, vino, ellos no Lo recibieron,
sino que se pusieron en Su contra, tomando consejo contra Él para destruirle,
aunque en palabras decían que Lo esperaban fervientemente.
Así es ahora.
Porque hay muchos en este día que profesan con sus palabras
que creen en Su venida en la carne y en Sus sufrimientos,
muerte, resurrección y ascensión; sin embargo,
teniendo una fe que consiste en conceptos externos,
y no en una experiencia interna del propósito de Su venida,
ni de la virtud de Sus sufrimientos, muerte, resurrección, etc.,
siguen siendo enemigos en su mente a Su segunda aparición
y venida "`sin pecado para salvación.`"^
footnote:[Hebreos 9:28 RV 1602 purificada]

Así pues,
hay una necesidad de que todos los hombres vengan
y obedezcan a esta Semilla divina y espiritual,
que ha sido puesta en sus consciencias por el Dios viviente,
para que por ella el ojo espiritual sea abierto,
el cual ha sido cegado por el dios de este mundo a través de la desobediencia.
Porque hasta que esto no sea hecho en alguna medida,
el misterio de la piedad (que es grande) no puede ni ser visto ni entendido.
Fue por esta razón que Cristo (quien era y es ese gran misterio,
y el don del amor del Padre), al darse cuenta de que la mujer de Samaria no Lo conocía,
le dijo: "`Si conocieses el don de Dios, y quién es el que te dice: Dame de beber:
tú pedirías de Él, y Él te daría agua viva.`"^
footnote:[Juan 4:10]

El gran anhelo espiritual de los mensajeros y siervos del Altísimo en eras pasadas,
era la misma que la de ahora, a saber:
"`Convertir a las personas de las tinieblas a la luz,
y de la potestad de Satanás a Dios.`"^
footnote:[Hechos 26:18]
Esto de ninguna manera invalida la manifestación de Cristo en ese cuerpo físico,
ni Sus sufrimientos, muerte, resurrección o ascensión; sino más bien,
lleva a todas las personas a eso que les abrirá los ojos de sus entendimientos,
de tal modo que vean y conozcan el beneficio que recibieron
por la aparición externa del Salvador del mundo.
Porque esto testificamos,
que por esa única ofrenda son hechos perfectos todos los que son santificados.^
footnote:[Hebreos 10:14]

Pero aquí se levanta otra objeción de parte de algunos,
que pueden llegar al punto de reconocer y confesar que hay
una Semilla o luz en el hombre que descubre el pecado,
y que enseña al hombre a actuar justa y equitativamente (lo cual algunos llaman moralidad).
Por falta de entendimiento,
muchos de estos niegan que esta luz o Semilla en el hombre tiene la capacidad de salvar,
o que es de la naturaleza y esencia del Ser Divino, y por lo tanto se oponen a la Verdad,
y tropiezan con esa Piedra de Ángulo que en todas las generaciones
ha sido una piedra de tropiezo y una roca que hace caer.
Sí, muchos son considerados sabios edificadores, profesantes de Dios y de Cristo,
quienes, habiéndose entregado a ser guiados por su propia sabiduría y opinión,
y siendo ignorantes de la raíz y el linaje de David, rechazan esta Piedra de Ángulo.

Ahora,
por el bien de todos los que desean el conocimiento verdadero y salvador de Cristo Jesús,
está sobre mi espíritu abrir aún más la naturaleza y propiedad de esta Semilla y luz;
cuya fuente es el Ser Eterno y océano inagotable de Plenitud Divina,
y cuya naturaleza y esencia es una con la Fuente de la que viene.
Juan testificó: "`En el principio era la Palabra, y la Palabra era con Dios,
y la Palabra era Dios,`" etc.
"`En Él estaba la vida, y la vida era la luz de los hombres.`"
Él también testificó que Juan el Bautista no era esa luz, sino que vino por testimonio,
para que diese testimonio de que la Luz verdadera era eso
que alumbra a todo hombre que viene a este mundo.
Así que el origen de esta luz es Cristo Jesús, la Palabra.
Pero algunos pudieran preguntarse: ¿Es Cristo la luz que está en todo hombre?

A esto respondo: Cristo aparece mediante Su luz en todo hombre;
y la luz que viene de Cristo está en todo hombre,
como se muestra claramente en las Escrituras de la Verdad.^
footnote:[Juan 1:9; Romanos 1:19, Tito 2:11, Juan 16:8]
Y aunque considero innecesario responder a las preguntas
curiosas de aquellos que buscan saber mucho,
pero no caminan conforme a lo que ya saben; aún así,
por el bien de aquellos cuyos entendimientos no han sido abiertos,
y están preguntando por el camino a Sion, les ofrezco esta analogía:
El sol natural es establecido por el Creador para iluminar el mundo externo,
el cual manifiesta desde sí mismo una medida de su luz y propiedad natural,
que brilla sobre justos e injustos,
y así transmite esa virtud que es inherente en sí mismo.
Cuando el sol brilla sobre cualquier cosa, nosotros a veces decimos:
"`El sol ha aparecido ahí;`" y otras veces decimos:
"`Ahí está el sol;`" y supongo que nadie negará que estas expresiones son correctas.
Porque en esa aparición la luz es vista y la virtud es sentida,
la cual penetra de tal modo que refresca nuestros cuerpos naturales,
y esta luz y calor son inseparables de la plenitud.
Y aunque el sol brilla diariamente y despliega su
vida poderosa en y sobre toda la tierra y sus habitantes,
aun así,
el cuerpo del sol de ninguna manera se agota ni se altera a lo largo de las eras y generaciones.
De forma similar, Cristo (la fuente universal de vida, el Sol de justicia,
el océano y plenitud de luz, vida y virtud espiritual,
de quien es transmitida una medida de Su naturaleza,
propiedad y esencia) es dado por el Padre para alumbrar
a todos los hijos e hijas de los hombres,
quienes, por lo tanto, son iluminados con Su aparición espiritual.
Y aunque esta aparición espiritual no puede considerarse como la plenitud, aun así,
siendo una medida de esa plenitud, es una en naturaleza y propiedad con la fuente,
y no puede separarse de ella.
Y aunque a través de su virtud, se transmite vida diariamente a los hijos de los hombres,
que esperan Su aparición como la luz del alba, y no pueden vivir para Dios sin ella,
aun así, la Fuente no experimenta ninguna reducción o cambio,
sino que toda la plenitud de la luz, vida y gloria Divina,
permanece y permanecerá con Él a través de cada era y generación.

Ahora bien, debido al velo de las tinieblas que ha cubierto los corazones de los hombres,
cuando nosotros damos testimonio de la aparición universal del Sol de
justicia en los corazones de todos los hijos e hijas de los hombres,
algunos están listos para decir que tal testimonio tiende a disminuir
esa gloria y honor que le pertenecen a Él como la plenitud,
y como Aquel que está sentado a la diestra del Padre;
implicando que mientras nosotros testificamos de Su aparición en nuestros corazones,
estamos excluyendo la posibilidad de que Él esté presente en otros lugares.
Sin embargo,
esta deducción es tan irracional como lo sería si alguna persona concluyera que,
porque nosotros decimos con respecto al resplandor y aparición del sol,
"`Ahí está el sol,`" o "`El sol ha aparecido ahí,`" nosotros, por lo tanto,
negáramos que el sol existiera en otro lugar.
Porque todos sabemos que su virtud es transmitida a nuestros cuerpos naturales,
teniendo cada uno en medida algún beneficio de la virtud o luz del sol natural,
que es luz para el ojo del cuerpo natural.
De forma similar,
aquellos cuyos sentidos espirituales han sido vivificados
por la virtud que procede del Sol eterno de justicia,
disciernen así las cosas espirituales de acuerdo con la
manifestación clara de la Verdad en su interior.
Y a partir de la experiencia de esto,
ellos pueden dar un testimonio certero de que Cristo, el Señor,
por Su Espíritu Santo y vivificante,
ha aparecido en ellos para dar vida a sus almas inmortales;
y también dan testimonio de que, por creer en la luz, y obedecer Su aparición,
han salido de ese estado que es reprobado por el Señor,
y pueden decir con certeza y experiencia que "`Cristo está en nosotros,
esperanza de gloria.`"^
footnote:[Colosenses 1:27]

Y, por lo tanto, cuando dirigimos a las personas a esta Palabra, Semilla, Luz, Ley,
Gracia y Espíritu,
jamás pretendemos poner en duda el hecho de que Cristo Jesús (la
luz del mundo y el don de Dios) es el verdadero Salvador y Redentor,
y Aquel que reconcilia la humanidad con Dios.

Ahora bien, esta luz (y Espíritu) lleva al alma de todos los que la obedecen, a Dios,
la fuente de la cual viene; y ningún hombre puede ver su naturaleza,
salvo aquellos que son guiados por ella.
Porque es solo en la luz del Señor que el hombre llega a ver la luz,
y a tener un verdadero entendimiento.
Y antes de que esto pueda ser visto o entendido plenamente,
la mente del hombre debe ser humillada y sacada de sus propios deseos y actividad,
de su propia comprensión y búsqueda, y llevada a esta luz,
para que en ella experimente la muerte a su propia voluntad,
y sea comprendida en esta luz.
Así el hombre llega a tener "`un entendimiento para conocer al que es verdadero,
y para estar en el verdadero.`"^
footnote:[1 Juan 5:20]

Ahora bien,
a medida que alguno es convencido y convertido por esta Semilla celestial
(que ha sido puesta en la consciencia para ser guía y líder de la humanidad),
en esa misma medida es sacado de las tinieblas en las que se encontraba.
Porque la luz resplandece en las tinieblas,
pero mientras que el hombre permanece en tinieblas,
no puede comprender esta luz o gracia celestial.
La luz a veces se mueve por las tinieblas, sobre el entendimiento del hombre,
reprobando y descubriendo las tinieblas,
y haciendo que él escuche su voz suave y delicada.
En verdad, mientras que el hombre continúa en rebeldía y desobediencia,
la luz lo reprende diariamente, durante todo el tiempo de su visitación,
y también lo aprueba y le concede paz cuando es obediente.

Aunque un hombre puede alejarse y apartarse de ella, y rebelarse contra ella,
y de este modo volverse como uno de esos de quienes habló Job,
que por ser "`rebeldes a la luz, nunca conocieron sus caminos,`"^
footnote:[Job 24:13]
dando lugar a la obra del dios de este mundo para así ser arrastrados a lo externo,
a las cosas que se desvanecen y perecen; aun así,
la luz permanece sin variación en sí misma, siendo y viniendo de un Ser inmutable,
y ella permanece en el hombre hasta que le sea quitada,
y él sea echado a profundas tinieblas.

Jesús comparó este don del Padre con un grano de mostaza,
y con un poquito de levadura que una mujer tomó y escondió en tres medidas de harina,
hasta que todo fue leudado.
La primera operación de esta luz celestial en aquellos que son convencidos por ella,
y que se han vuelto a ella,
_es mostrarle al hombre su verdadero estado y condición._
Por lo tanto,
el primer paso en el camino de la vida es volverse a esta Semilla santa,
que enseña al obediente a conocer correctamente a Dios.
Y cuando un hombre llega a tener un verdadero sentido de su estado caído,
y a ver cómo se ha rebelado contra ese Ser eterno que le dio vida y aliento,
y que ha esperado mucho tiempo para tener piedad de él,
y que toca la puerta del corazón y contiende con él mediante Su luz Divina, yo digo,
el sentido de esto le quebrantará el corazón,
y enternecerá el espíritu ante el Señor. Y bajo el
peso de la gran carga del pecado y la iniquidad,
habrá un clamor: "`Mis pecados como carga pesada se han agravado sobre mí,
y mis iniquidades se han agravado sobre mi cabeza.`"^
footnote:[Salmos 38:4]
Diciendo, cómo dijo Pablo:
"`¡Miserable hombre de mí! ¿Quién me librará del cuerpo de esta muerte?`"^
footnote:[Romanos 7:24 RV 1602 Purificada]
Aquí es abierto el ojo que ve a Aquel a quien el hombre ha traspasado y expuesto a vituperio;
y entonces habrán días de llanto y lamento debido a Él;
y en verdad este es "`el tiempo de angustia de Jacob.`"^
footnote:[Jeremías 30:7]

En el sentido de este estado caído y lamentable, de la inmensa paciencia del Señor,
y de la larga contienda de Su Espíritu, ustedes verán que, en la justicia de Dios,
la muerte eterna podría ser su porción. Pero eso que los lleva a sentir esto,
también engendra en el alma un clamor secreto por un Redentor y Salvador,
lo cual además les dará un verdadero entendimiento de que
no hay otra manera por la que sus almas pueden ser redimidas,
salvo en y por las misericordias del Señor Jesucristo--__misericordias que sólo comenzarán
a obrar eficazmente en ustedes al andar en el camino de los juicios del Señor,__
porque "`Sion es rescatada con juicio, y los convertidos de ella con justicia.`"^
footnote:[Isaías 1:27]
Y aquí también verán que la medida que falta de las
aflicciones de Cristo debe ser cumplida en ustedes;
porque no hay otro camino por el que el hombre pueda pasar a la vida, la paz y el gozo,
con el Padre de los espíritus,
salvo el camino por el que ha pasado el Capitán de la salvación,
que fue a través de la muerte; y aquí comenzarán a "`armarse del mismo pensamiento.`"^
footnote:[1 Pedro 4:1]
Porque ninguno ha terminado con el pecado más allá de lo que ha
sufrido en la carne la crucifixión de sus pasiones y deseos.^
footnote:[1 Pedro 4:1-2]
Y aquí el objetivo de la predicación del Evangelio llega a ser conocido y atestiguado,
el cual es, __que todos "`sean juzgados en carne según los hombres,
pero vivan en espíritu según Dios.`"__^
footnote:[1 Pedro 4:6]
Y en este trato interno, el Señor Dios Todopoderoso inclinará Su oído,
responderá el clamor de sus almas despiertas, y manifestará Su Palabra de poder.
Y todos los que están en este estado sentirán que dicha
Palabra es más aguda que toda espada de dos filos,
y que penetra hasta partir sus almas inmortales del espíritu y naturaleza de
transgresión y de su operación diaria (a medida que le rindan sujeción y obediencia
a ella) haciendo una separación entre las coyunturas y los tuétanos,
y dándoles un discernimiento de los pensamientos y las intenciones de sus corazones.^
footnote:[Hebreos 4:12]

Y a todos los que sienten clamores verdaderos,
respiraciones vivas y deseos fervientes en sus almas, por experimentar esta bendita obra,
yo les digo:
humíllense con ternura de espíritu y sinceridad de corazón ante esta Semilla del reino,
aunque ella sea como un grano de mostaza.
Manténganse bajos internamente, y amen esa luz que descubre la semilla de la serpiente;
amen sus operaciones y movimientos en el corazón. Sufran con ella,
lloren y laméntense con ella,
y entréguense no solo a los descubrimientos de la Semilla del reino,
sino también a los juicios que ella trae,
para que la naturaleza y las obras de la semilla de la serpiente sean destruidas.
Porque el alma nunca podrá llegar a ser una con la Semilla incorruptible,
ni nacer de ella (en la cual todas las promesas son sí y amén) sino a través del desgaste,
mengua y destrucción de la naturaleza y obra de la semilla de la serpiente,
que ha sido como una separación o pared intermedia
entre el alma y Cristo Jesús. Por lo tanto,
al volverse pasivos y sumisos al poder de Dios,
y a la obra de esta Semilla en su aparición más pequeña y baja,
todos serán llevados a un espíritu muy humilde y tierno,
y sus corazones y almas se llenarán del temor y reverencia del Altísimo.
Y estos se volverán verdaderamente cuidadosos,
y serán diligentes en prestar atención a sus movimientos secretos,
y a sus operaciones dulces y poderosas en el alma,
siendo cautelosos de no menospreciar ninguna de ellas.
Y si ustedes con diligencia y constancia se aferran con sus almas a ella,
van a sentir y ver (mientras su fe permanezca en
ella) que la operación de ella es como la levadura,
que los leuda y transforma a la naturaleza divina.

Por lo tanto, no se cansen de tomar la cruz de Cristo,
ni de soportar los tiempos de luto bajo los profundos tratos espirituales;
sino que perseveren diariamente en el amor de esta Semilla inmortal; porque entonces,
naciendo y creciendo en el poder de sus operaciones en el alma,
serán nutridos tiernamente por eso que es de la misma naturaleza, a saber,
la leche espiritual de la Palabra, que vive y permanece para siempre,
de la cual han sido engendrados.
Y por ella crecerán hasta llegar al día de la boda
en la cámara de matrimonio del amor y vida divinos,
donde el alma está segura en el disfrute del indescriptible
gozo del Señor Dios y del Cordero para siempre.

Así entonces, a medida que el alma se entregue en amor a Dios,
a seguirlo resueltamente en el camino de Sus juicios,
y entregue a la espada del Señor lo que es para la espada,
y a destrucción lo que es para destrucción,
en esa medida la preciosa obra del Señor prosperará.
Y aunque esto sea un tiempo de aflicción,
dolor y angustia, aun así, es un buen día. Por lo tanto,
no se esfuercen por salir de debajo de este día, ni intenten terminarlo apresuradamente;
porque la tristeza verdadera que es según Dios produce un arrepentimiento verdadero,
de que no hay que arrepentirse.
Después del arrepentimiento verdadero,
viene la verdadera experiencia de remisión y perdón;
y así sus iniquidades llegarán a ser borradas por los juicios del Señor,
y entonces vendrán de la presencia del Señor, y de la gloria de Su poder,
tiempos de refrigerio.

Por lo tanto, en el nombre de Aquel que vive para siempre,
les digo a todos en todas partes,
_vuélvanse a su interior, vuélvanse a su interior, vuélvanse a su interior._
Vuélvanse rápidamente a la naturaleza divina sembrada en su corazón,
que será el único refugio seguro en el día terrible
del juicio del Dios Todopoderoso que viene pronto.
Y en Su nombre les advierto a todos los que han dejado
la obediencia a la cruz diaria de Cristo Jesús,
y no han permanecido en la vigilancia diaria y santa,
(y por lo tanto han obtenido una libertad falsa en sus caminos, palabras, conducta,
comida, bebida y apariencia),
que regresen rápidamente a su interior y se sometan a la
operación del cuchillo espiritual de la circuncisión;
para que todo lo que ofende al Señor,
y contrista Su buen Espíritu sea cortado y removido efectivamente,
y ustedes sean llevados a velar en temor y reverencia en la luz del Cordero.
Lleven el yugo del Señor Jesús, y amen Su cruz celestial,
que crucifica todas sus inclinaciones a la vanidad y a los placeres vanos.
No dejen que nada se interponga entre ella y ustedes; y así crecerán diariamente,
de un grado de fuerza y estatura a otro.
Y en la luz, verán las trampas y tentaciones del enemigo,
y permanecerán en una diligencia viva e interna,
fuera del estado de las vírgenes insensatas (donde
la ociosidad espiritual produce sueño espiritual,
lo cual hace que el aceite se pierda, y entonces la lámpara se apague).
Pero permaneciendo en sujeción diaria a la cruz celestial,
en la vigilancia santa, crecerán a la estatura de joven, en la cual se vuelven fuertes,
y la palabra de Dios permanece en ustedes; y permaneciendo en ella, vencerán al maligno,
y evitarán ser como aquellos en quienes la semilla cayó junto al camino,
en pedregales o entre espinos.

Porque a medida que se permanezca fielmente en la vigilancia interna,
y en la obediencia continua a esta luz celestial (en la
que se experimenta el principio de la obra de Dios),
habrá un avance paso a paso en las huellas del rebaño de Cristo Jesús,
y un crecimiento de un grado de fuerza a otro, sobre el pecado y su naturaleza,
y de un grado de gracia a otro.
Así, el ojo del entendimiento será bueno,
y aquí todo lo que es tropiezo será visto y el alma
no dejará de experimentar una lucha interna,
hasta que eso que lo detiene sea quitado de en medio,
y hasta que todo el dominio y autoridad del enemigo
sea sometido bajo los pies del ungido del Señor,
y el principado en el alma esté sobre Su hombro, cuyo derecho es reinar, sobre todo.

Y aquí la salvación, redención y restauración se disfrutan efectivamente,
por medio de la fe y la operación eficaz del Omnipotente poder de Dios,
a quien sea la gloria de Su propia obra para siempre.
Aquí habrá un crecimiento e incremento,
hasta que se llegue a ese precioso estado e imagen
en el que el hombre estaba antes de la caída.
