== Los Desvíos, Caminos Torcidos, Artimañas y Trampas del Enemigo Descubiertos

Ahora bien, cuando la mente se vuelve a esta Semilla Divina y celestial,
y la obra del Señor ha comenzado,
el mismo destructor que llevó al hombre a la esclavitud al principio,
y que lo ha mantenido en esa esclavitud, empezará a obrar sutilmente,
y se esforzará por destruir la obra que Dios ha comenzado en el alma.
Y para lograr su propósito, anda por todos lados al acecho, buscando una entrada,
y hará que sus tentaciones estén amoldadas a las
propensiones e inclinaciones de cada persona.

Si el corazón está abatido bajo un fuerte sentido de iniquidad y de muchas transgresiones,
a través del cual el dolor y la amargura se han vuelto muy grandes,
entonces el enemigo comenzará a "`disfrazarse`"^
footnote:[2 Corintios 11:13-15]
de luz, aunque en naturaleza es contrario a ella.
Porque, aunque la verdadera luz da un entendimiento correcto del estado interno,
y produce tristeza por causa del pecado, y revela la montaña de iniquidad, aun así,
ella también engendra una secreta esperanza de vencer por medio
de la fuerza del Señor. Pero cuando el enemigo ve al alma abatida,
a menudo la aflige y la lleva a creer que nunca vencerá,
intentando de este modo hundirla en la desesperación; sabiendo que, si él vence,
seguirá teniendo al alma bajo su poder.
Pero si todos los que están en este tiempo de prueba,
tan sólo esperaran en el Señor con un corazón sincero, y con la mente puesta en la luz,
ellos descubrirían esta trampa.
Porque, como he dicho,
aunque la aparición verdadera de la luz y gracia
celestial de Dios produce un día de aflicción,
dolor y angustia, aun así, esta tristeza no es una tristeza sin esperanza.
Pero la operación del enemigo busca llevar al alma a una tristeza sin esperanza,
y arrastrar al espíritu hacia abajo, hacia las cámaras de la oscuridad.

Cuando esta trampa es descubierta,
y el alma (por medio del amor y poder de Dios) es consolada y refrescada,
y levantada con una medida de esperanza viva,
entonces el enemigo se esfuerza por alejarla de los dolores de parto internos y diarios,
para que el juicio no sea llevado a la victoria;^
footnote:[Mateo 12:20 LBLA]
y por lo tanto,
atrae la mente hacia una persuasión falsa de que está siendo obediente y diligente cuando
realmente no está permaneciendo en esa luz que le da un verdadero sentido de su condición.
Y así como antes deseaba destruir la esperanza que es como un ancla segura y firme,
ahora trata de engendrar una falsa esperanza y confianza,
y sacar al alma de debajo de la cruz diaria,
por la cual la naturaleza que es ajena a Dios debe ser destruida.

Y si el enemigo es visto y vencido en estas dos trampas,
y la obra interna prospera al punto de que mucho ha sido sometido,
y mucho ha sido crucificado por medio de la obediencia diaria al poder celestial,
y el corazón llega a ser purificado en una buena medida,
y a tener un buen progreso a través del ministerio
de condenación (que es glorioso en su tiempo),
y algo de la paz pura y del gozo celestial se levanta en el corazón--en este punto,
el enemigo volverá a tratar de engañar con sutileza, persuadiendo al alma a reposar aquí,
como si todo ya estuviera hecho,
y así hacer que se aleje y deje de alimentarse del árbol de vida,
y se alimente del árbol del conocimiento del bien y del mal,
y quiebre el mandamiento del Señor. Primero él sutilmente
lleva la mente hacia lo externo a tomar un poco de libertad,
fuera de esa vigilancia y temor diligentes en los que estaba antes.
Y si el enemigo prevalece en esto, alejará aún más el alma de la vida inocente,
y gradualmente abrirá un ojo que ve algo deseable
en las cosas externas que atrae la mente.
Y mientras que él prevalezca gradual y secretamente en esto,
el ojo verdadero que había sido abierto llegará a ser (por
medio de la desobediencia) cegado en alguna medida;
y aquí se experimentará una pérdida,
incluso antes de que se de cuenta el que no es vigilante.

Así que la primera obra del enemigo es hacer que estos naufraguen
en cuanto a la fe en una medida pequeña,
de modo que su creer diario ya no esté fundado en el poder.
Y a medida que pierden gradualmente el disfrute diario de esto,
se apartan progresivamente del poder de la piedad a la mera forma externa.
Y aunque a veces el poder del Señor se puede sentir todavía en este estado, aun así,
debido a que el alma deja de buscar y disfrutarlo
como su verdadero refrescamiento y consolación,
se erige una falsa imagen en su lugar.
Entonces el enemigo presenta algunos objetos para ocupar la mente,
y así entrar gradualmente en ella y profanarla, y alejarla de su verdadero Guía,
y de esta manera hacerla naufragar en cuanto a la buena consciencia.

Si el enemigo es descubierto en este punto (antes de que lleve a cabo su obra y traiga
la muerte y la oscuridad sobre el alma otra vez) y el poder del Señor rompe sus trampas,
y concede un sentido verdadero de ellas,
a través del cual viene tristeza y angustia al alma--aquí
él volverá a disfrazarse y a obrar tal como lo hizo al principio,
haciéndose pasar por el poder del Señor que condena.
De este modo trata de llevar la mente a la desesperación,
haciéndola creer que nunca podrá recuperar su condición anterior,
y también a mirar a aquel que la ha envenenado, para que el remedio (a saber,
el poder del Señor que redime el alma) no sea anhelado ni buscado.
Pero si el alma es verdaderamente sumisa al Señor,
y "`espera en Él en el camino de Sus juicios,`"^
footnote:[Isaías 26:8]
deseando que toda la fe y la confianza provengan de Su poder,
entonces la rebelión será sanada.^
footnote:[Jeremías 3:22]
Y así, al volver a la luz y mantenerse diligentemente en ella,
el poder del Señor Dios vencerá eso que ha buscado destruir como león rugiente,
y entonces conducirá al alma de nuevo en el camino.

Pero cuando se experimenta la liberación de esta trampa mortal,
y la obra continúa prósperamente hasta al punto en que la casa es limpiada y ordenada,
y se siente cómo el alma pasa de muerte a vida;
y cuando ella ha pasado por el ministerio de condenación,
y el espíritu que gobernaba en el estado desobediente ha sido echado fuera,
y la ministración del Espíritu (que es mucho más gloriosa) es sentida--entonces
el enemigo se disfrazará otra vez de ángel de luz,
y con todo su poder y fuerza, obrará por medio de tentaciones a diestra y siniestra.
Porque cuando hay revelaciones en el entendimiento, y profecías,
y cuando brota el gozo en el corazón por medio de la operación del poder eterno,
entonces el enemigo obra secretamente para sacar la mente
del valle de la humillación. Y si prevalece en esto,
él se esforzará por llevar a extremos,
y así confundir la mente y hacerla correr a nociones imaginarias,
con el fin de deshonrar el nombre del Dios vivo y socavar Su obra.
De este modo busca destruir el verdadero nacimiento,
que ha sido dado a luz por medio de angustia y dolores de parto.

Si el enemigo no puede prevalecer aquí, sino que la luz del Señor lo descubre,
entonces él hará lo posible por sacar la mente de la vigilancia y del temor diario,
y de la libertad de los hijos de Dios,
cuya libertad es solo para servir al Señor. Porque
cuando se siente dominio en alguna medida,
se disfruta de consuelo y consolación,
y se levantan en el corazón alabanzas a Aquel que ha visitado y redimido el alma.
Pero en este punto el enemigo estará listo para sacar la mente de ese
estado firme de mansedumbre y vigilancia constante en la luz,
para así hacer que el alma desperdicie su porción (como el hijo pródigo),
y malgaste su herencia al correr antes de la guía y los
movimientos del poder del Señor--hablando mucho del gozo,
de las profecías y revelaciones,
pero no siendo guiado a ello por ese poder que abrió el corazón al principio.
Aquí se da a luz un nacimiento prematuro, que se marchitará y quedará en la nada.

Y si el enemigo no vence por medio de estas trampas y tentaciones, él no cesará,
sino que "`como león rugiente, andará alrededor buscando a quien devorar`"^
footnote:[1 Pedro 5:8]
y cómo lograr entrar otra vez.
Pero él pone sus tentaciones según el espíritu, crecimiento,
capacidades e inclinaciones de cada individuo.
Después de que la buena obra de Dios ha comenzado,
y el brazo de Su salvación ha sido revelado maravillosamente
para sacar del Egipto espiritual de oscuridad,
y después de que Él ha ejecutado muchas salvaciones innegables del enemigo destructor,
y a menudo ha alimentado al alma con comida celestial,
y hecho que la roca diera agua para saciar la sed,
y después de que muchos desvíos y rebeliones en el desierto
han sido vistos y descubiertos por el poder eterno,
y hay un cruce del río del juicio,
y el gran poder de Dios expulsa al enemigo que ha habitado
en la tierra donde solo debe morar la Semilla de Abraham,
y la guerra cesa en gran medida, y parte de la buena tierra es poseída y disfrutada,
es decir,
la tierra que fluye leche y miel espirituales--aquí
también el perverso y sutil enemigo estará obrando,
como lo hizo con el Israel externo, haciendo que "`Jesurún engorde, y tire coces`"^
footnote:[Deuteronomio 32:16]
contra el poder.
Porque en el caso de aquellos que han llegado hasta aquí,
la serpiente busca sacar la mente de lo interno,
por medio del disfrute de aquello que es bueno en su lugar,
y llevarla a un estado de reposo falso,
para que menosprecie la Roca de su salvación y así olvide
al Señor que formó al hombre y lo llevó a la tierra de reposo.
De este modo él saca al alma del disfrute interno de la virtud,
haciendo que los hombres erijan ídolos en su corazón,
y así sirvan a dioses creados por ellos mismos,
teniendo una profesión de la verdad sin poseer la vida.

El antiguo enemigo ha logrado llevar a muchas personas a esta condición, las cuales,
en diferentes épocas, han visto las maravillosas obras del Señor,
y Su brazo extendido y engrandecido delante de sus enemigos; sin embargo,
se apartaron del Señor, y del sentido interno de Su poder.
Y entonces, el espíritu que había sido echado anteriormente,
y que andaba por lugares secos, toma con él siete espíritus peores y regresa, tienta,
prevalece y entra, y el postrer estado es peor que el primero.
Porque al principio, aunque el enemigo tenía el poder y el dominio, aun así,
había una consciencia de esto, y el corazón fue humillado,
hecho tierno y llevado a la verdadera pobreza,
y había un gemido delante del Señor por la falta de dominio.
Y el Señor,
en este estado de humillación y quebrantamiento de corazón (en
el cual Él se complace) visitó al alma en Su infinita misericordia
e hizo que Su poder redentor y salvador fuera revelado.
Pero ahora, en este otro estado, la mente es altiva, el corazón está gordo, lleno,
en reposo y se ha sumergido en el amor del mundo y de las cosas del mundo,
y por esto se ha olvidado del Señor, quien al principio era buscado cada día,
y esperado diligentemente.
Así la Roca (el poder de Dios) es menospreciada;
porque el corazón está puesto en otra cosa.
Y aquí han sido cometidos dos grandes males juntos,
a saber: Ellos dejaron la Fuente de misericordias vivas,
y han cavado para sí cisternas rotas^
footnote:[Jeremías 2:13]--es decir, una profesión cristiana que no retendrá agua;
que no retendrá un refrescamiento, gozo, paz o consuelo que permanezcan.

De este modo el enemigo ha prevalecido a lo largo de muchas eras,
por medio de su operación progresiva y su sutileza,
alejando a miles del disfrute de Dios en un espíritu puro, tierno y recto.
_Y el primer paso que siempre da para lograr esto,
es sacar la mente de la vigilancia constante y diaria (casi imperceptiblemente),_
y así hacer que la mente carnal tome un poco de libertad (con un cierto gozo
o dulzura en ella) por medio de la cual el ojo de la mente es entenebrecido,
y el alma es seducida a buscar más libertad.
Algunas veces él empieza por atraer al alma fuera de la obediencia
a esas cosas que fueron requeridas en "`el día de las pequeñeces;`"^
footnote:[Zacarías 4:10]
quizás hacia el uso de muchas palabras,
para no seguir siendo como un "`portero en la casa del Señor.`"^
footnote:[Salmo 84:10]
El enemigo se esfuerza por hacer que esas cosas se vean pequeñas e irrelevantes,
para así quitar el tropiezo de la cruz.
Entonces la mente corre a "`proveer para los deseos de la carne,`"^
footnote:[Romanos 13:14]
ya sea en comida, bebida,
apariencia o cualquier cosa semejante que la Verdad (en el pasado) había puesto de manifiesto,
y que el poder de Dios (la cruz de Cristo) había juzgado,
llevando al alma a la vigilancia y al temor puro,
a no proveer en ningún aspecto para los deseos de la carne.
Porque la Verdad lleva al corazón a la sencillez (tanto en práctica como en principio),
y saca de todas las superfluidades,
permitiéndole a la criatura satisfacer sus necesidades naturales,
pero no alimentar sus deseos.

Pero, aun así, el enemigo opera progresivamente,
sacando de manera sutil y encubierta de la libertad de la cruz
de Cristo Jesús (que es el poder de Dios para salvación),
y llevando a la libertad de la carne.
De este modo obtiene una mayor entrada,
operando gradualmente para llevar la mente a muchas palabras (ya
sea en sus negocios o conversaciones) o hacia el amor del mundo, etc.
Y aunque aquí muchas veces se puede sentir el poder
de Dios (en alguna medida) buscando sacar de la trampa,
aun así, debido a que el dios de este mundo ya ha cegado mucho el ojo,
y entenebrecido el entendimiento,
no hay una percepción clara del poder del Señor en Sus operaciones,
ni de la sutileza del enemigo.
Y aunque un hombre puede (en gran medida) mantener sus creencias
religiosas y su conformidad externa con la verdad,
aun así, el enemigo puede obrar debajo de todo eso sin ser descubierto,
por falta de vigilancia, y así (paso a paso) lleva fuera del poder de la piedad,
hasta asesinar el nacimiento que había sido engendrado en
los primeros días de la misericordiosa visitación de Dios.
Y luego comienza a crecer el orgullo en el corazón,
y en esta condición los hombres considerarán la operación del poder
de Dios como "`extremos`" e "`imaginaciones,`" y tirarán coces
(como Jesurún) y se volverán contra el poder de Dios,
porque prefieren una semejanza e imagen.
A estos les encanta escuchar cosas agradables de la sabiduría de los hombres dotados,
que han perdido su camino por apartarse del poder y no esperar en todas
las ocasiones para ser guiados por él. Y aquí encontramos la "`comezón
de oír,`" y el "`amontonar maestros conforme a sus concupiscencias.`"^
footnote:[2 Timoteo 4:3]
Y aquí Jezabel es sostenida; cuyo error entró a la iglesia de Tiatira,
y ha continuado en todas las edades,
donde sea que los hombres hayan dejado el estado contrito y tierno,
y permitido y nutrido a esta Jezabel,
la cual debe ser "`echada a la cama de tribulaciones,
y todos sus hijos heridos de muerte.`"^
footnote:[Apocalipsis 2:20-23]

Todas las operaciones del enemigo, bajo cada disfraz,
tienen como fin matar eso que fue vivificado,
y llevar al alma a contentarse con una profesión externa del camino de la verdad,
luz y vida de Cristo Jesús (el poder de Dios para salvación),
cuando el corazón se ha apartado del Señor y ha abrazado otros amantes.
Donde el enemigo prevalezca de este modo,
en el transcurso del tiempo llevará a todos de regreso al mundo,
del cual el brazo del Señor los había recogido;
y el postrer estado de estos será peor que el primero.
Porque habiendo naufragado en cuanto a la fe y buena conciencia,
la segunda muerte viene sobre ellos, y estos por lo tanto están "`dos veces muertos,`"^
footnote:[Judas 1:12]
y son como la sal que ha perdido su sabor,
que no sirve más para nada sino para ser echada fuera y hollada por los hombres.
La única forma de ser preservado fuera de todos estos desvíos, caminos torcidos, engaños,
trampas y tentaciones del enemigo,
_es esperando en la luz (que es el don y gracia de Dios),
y permaneciendo sinceramente en ella,
en la cual se experimentan las revelaciones y manifestaciones
diarias del poder eterno de Dios._
Porque en el conocimiento y experiencia de esto,
el corazón es mantenido humilde y tierno,
y de ahí surgen respiraciones y anhelos internos en pos del disfrute diario de la vida,
poder y virtud refrescante,
que es lo único que renueva e incrementa la fuerza del hombre interior.
Que el Dios Altísimo preserve a todos los viajeros a Sion en este camino hasta el fin.
