[short="Un Llamado a las Ovejas Esparcidas"]
== Un Llamado en el Amor de Dios, a Todas las Ovejas Esparcidas

Ahora escuchen y presten su oído,
ustedes que están esparcidos por las montañas estériles de profesión religiosa,
quienes habiendo perdido el sentido vivo que estuvo
en muchos de sus espíritus años atrás,
ahora están buscando al que vive entre las religiones muertas,
y pan en lugares desolados.
Recuerden los años pasados; traigan a su memoria los días en que eran tiernos,
cuando la luz de Dios resplandeció sobre su tabernáculo de tal modo que por ella ustedes
se vieron a sí mismos en tinieblas y en la separación del disfrute de su Creador.
El sentido de esta condición trajo un día de luto y de amargo lamento sobre ustedes,
y era la razón por la que ayunaban,
oraban y buscaban fervientemente al Señor con suspiros y lágrimas.
Esto hizo que algunos de ustedes establecieran tiempos
para reunirse a derramar sus almas,
deseando que el Dios vivo irrumpiera entre ustedes con Su presencia,
y revelara Su brazo de salvación. En este día ¡cómo muchos de ustedes se retiraban a
sus aposentos y lugares secretos a gemir delante del Señor! ¡Cómo sus clamores y anhelos
en pos del Señor eran más fuertes que los de aquellos que esperan la mañana!
Y en ese día ¿acaso no era la sustancia misma lo que ustedes buscaban, es decir,
la revelación del Hijo del amor de Dios en sus almas?

Ahora,
permítanme razonar con ustedes en el nombre de Dios todopoderoso--con todos aquellos
(entre todas las profesiones religiosas) en los que queda algo de ternura o deseos
en pos del Señor. ¿Qué fue lo que hace tantos años
despertó sus corazones para que buscaran al Señor de esta manera?
¿Qué fue lo que les dio la consciencia de sus propias condiciones internas,
e hizo que el pecado se viera sobremanera pecaminoso?
¿Qué era eso que sentían en sus mentes,
que luchaba contra la ley del pecado y de la muerte en sus miembros,
y que en alguna medida abría el ojo de sus entendimientos para que vieran la
idolatría y la superstición? ¿Qué era eso que sacaba sus corazones del mundo,
y hacía que esas cosas tuvieran poco valor en comparación
con eso que sus almas despiertas buscaban?
¿Qué era eso que los sostenía internamente en los sufrimientos,
cuando el impío bramaba como las olas del mar,
y cuando se burlaba de ustedes por la sencillez de su apariencia
o por la manera estricta de vivir de sus familias?
Recuerden sus muchas y innegables salvaciones.
Recuerden cómo el Señor les respondió en el día en que estaban tiernos.
¿Qué era eso que trataba sus corazones,
e inclinaba sus espíritus a la reforma verdadera?
¿No era la gracia de Dios?
¿No era esa luz que brillaba en su tabernáculo?
¿No resplandeció esta luz en sus corazones, e inclinó sus espíritus hacia Dios,
y comenzó la obra del Señor en ustedes?
¿Por qué se apartaron y no prosiguieron en conocer al Señor en el camino de Sus juicios,
cuando experimentaron un poquito de prosperidad?
¿Por qué buscaron salir de Sus juicios, antes de que fueran llevados a victoria?
Despiértense y regresen, ustedes que de este modo se han apartado,
siguiendo palabras vacías y andando errantes de una
montaña de profesión e imaginación a otra,
hasta gastar su porción y regresar a Babilonia, la ciudad de confusión,
de la cual el Señor los llama a salir, diciendo: "`Apresúrense, apresúrense a salir,
y no participen más con ella en sus pecados,
para que no reciban con ella parte de sus plagas, que vendrán rápidamente sobre ella,
y sobre todos los que se encuentren en su territorio.`"

Abran sus ojos, y vean, donde fue que ustedes se apartaron,
y por qué sus necios corazones han sido entenebrecidos.
Porque el enemigo, que, "`como león rugiente, anda alrededor buscando a quien devorar,`"^
footnote:[1 Pedro 5:8]
hizo que ustedes se apartaran de esta Semilla Divina (que los había despertado,
y había comenzado a hacer la obra de Dios en ustedes),
y los llevó a una mera profesión de palabras y condiciones
que los santos describieron en las Escrituras.
Pero los santos alcanzaron estas cosas al pasar de muerte a vida en obediencia
a la gracia de Dios que "`es dada a todo hombre para provecho.`"^
footnote:[1 Corintios 12:7]
Ellos experimentaron la guerra santa, y pelearon la buena batalla,
y así obtuvieron la victoria.
Por medio de la operación eficaz de la gracia la obtuvieron,
y no por simples conceptos y creencias respecto a las palabras de sus hermanos,
los profetas.
Así,
ellos fueron hechos partícipes de las promesas por medio de la
fe y la obediencia al y en el Espíritu eterno de santidad.
En este camino ellos llegaron a despojarse del viejo hombre--que
es una obra real y discernible--y a revestirse del nuevo hombre,
que es un verdadero cambio y traslado fuera del reino de satanás, fuera de su poder,
al reino del amado Hijo del Dios viviente, para así estar bajo Su poder.

Pero el enemigo de sus almas los apartó de este don de la gracia de Dios (que obraba
en ustedes en sus días de ternura) al llevar sus mentes a una gracia pretenciosa y conceptual,
y a profesar que por ella ustedes fueron salvos; sin considerar que,
con esta gracia falsa, sus almas inmortales continúan en esclavitud,
porque su fe consiste en conceptos y no en el poder de Dios.
Esta fe no es más que una creencia en lo que Dios ha hecho por ellos externamente,
pero no es la fe que los lleva a conocer y experimentar la obra de Dios internamente,
ni la obediencia de la fe que purifica la conciencia y vivifica para Dios.
Y tales han sido las imaginaciones altivas de algunos que son llamados ministros,
que han presumido enseñar y sostener un don de gracia que permite
libertad para la naturaleza carnal y que evade la cruz de Cristo.
Esta enseñanza es contraria a esa santa libertad que se
experimenta por la operación de la verdadera gracia de Dios.
Porque, aunque es cierto, como el apóstol dijo, que "`por gracia somos salvos`"^
footnote:[Efesios 2:5, 8], aun así,
cualquiera que predique esta gracia de tal modo que haga que los hombres crean que son
salvos de la condenación mientras sigan siendo transgresores de la ley justa de Dios,
no "`usa bien la palabra de verdad,`"^
footnote:[2 Timoteo 2:15]
sino que enseña como doctrina las imaginaciones de su propio cerebro.
Porque no es una mera creencia o asentimiento de la mente respecto
al poder de la gracia lo que puede satisfacer al alma inmortal,
o darle una verdadera seguridad de tener paz eterna con Dios;
sino que debe haber también una conformidad en el hombre interior a su poder,
de modo que el hombre llegue a ser creado nuevamente en Cristo Jesús para buenas obras,
y a ser santificado por completo; cuerpo, alma y espíritu.

Y he encontrado que los hombres,
en lugar de predicar la necesidad de conformarse al poder de la gracia,
han predicado un tipo de gracia universal (cuya expresión, en sí misma,
es buena y apropiada,
porque la gracia de Dios se ha extendido a todos) que justifica a las
personas pecadoras y no santificadas mediante una justicia imputada;
incluso de tal manera que ha llevado a muchos a concluir que están en un estado
de salvación aún cuando el pecado continúa reinando en sus cuerpos mortales.
No puedo evitar testificar que esto es un error tan grande,
y tan contrario a la ministración del Evangelio y al propósito por el cual Cristo
fue manifestado en la carne (que era salvar a las personas _de_ sus pecados,
de tal modo que ya no vivieran más en ellos), como el error de los escribas y fariseos,
que buscaban y creían en la justificación por las obras de la ley,
sin la justicia de la fe.

Así ha sucedido que muchos han convertido la gracia de Dios en una licencia carnal,
o se han apartado de la gracia de Dios a la indulgencia;
de modo que muchos profesantes del cristianismo se han vuelto ligeros y vanos,
y han corrido con los profanos "`al mismo desenfreno de disolución,`"^
footnote:[1 Pedro 4:4]
y habiendo crecido fuertes en la carne, llegaron a ser mucho en apariencia,
pero son pequeños y livianos en la verdadera balanza.
Y aquí, todos ustedes profesantes de la Cristiandad,
que se han apartado de la aparición espiritual de Cristo Jesús en sus corazones,
y ahora se encuentran profesando la condición y las obras de los santos,
sin ser guiados por el mismo Espíritu y poder--aquí, yo digo,
ustedes han perdido su camino, y se han apartado de su Guía,
el cual los hubiera llevado a la sustancia,
Cristo Jesús. Miles de personas ignorantes han sido llevadas,
por medio de la astucia engañosa de los hombres, a una profesión vacía de palabras.
Y cuando la manifestación del Espíritu de Dios (que es dada a todo hombre para su provecho^
footnote:[1 Corintios 12:7]) se ha movido en el corazón
para sacar la mente fuera de los caminos,
espíritu y naturaleza del mundo,
entonces el enemigo (que siempre está disfrazándose)
se encuentra cerca para engañar y seducir,
dirigiendo a las personas a esta u otra profesión religiosa,
o animándolos a seguir esta forma externa o esta otra sombra,
bajo la engañosa pretensión de que son las ordenanzas de Dios y de Cristo.
Aquí el sutil enemigo (que alegremente permitirá
que los hombres practiquen las cosas externas,
mientras pueda mantener su trono en el corazón) ha hecho
que muchos se aparten del camino estrecho de la salvación,
al alejarlos del verdadero Guía interno,
de "`la gracia de Dios que se ha manifestado para salvación a todos los hombres,`"^
footnote:[Tito 2:11]
y llevarlos a prácticas externas.
Y aquí "`el temor de Dios,
no es más que un mandamiento de hombres que les ha sido enseñado`"^
footnote:[Isaías 29:13]
por hombres que no experimentan la guía del Espíritu y poder de Dios;
y por lo tanto "`curan la herida de mi pueblo con liviandad, diciendo: Paz, paz;
y no hay paz.`"^
footnote:[Jeremías 6:14, 8:11]
y han "`recubierto con lodo suelto.`"^
footnote:[Ezequiel 13:10]

Y ahora, todos ustedes que están esparcidos sobre las montañas estériles,
escuchen el consejo y llamado del Señor: Vuélvanse, ustedes pródigos,
quienes han gastado sus porciones, y han perdido mucho de su sinceridad y ternura,
y de ese disfrute interno del Señor que tenían años atrás. Oh vuélvanse,
ustedes quienes por mucho tiempo han tratado de llenarse con algarrobas,
y con una profesión en palabras de lo que disfrutaron los santos antiguos.
Mi corazón suspira por ustedes,
y mi alma a menudo se siente agobiada por el sentido de su condición.
Mi corazón se duele dentro de mí cuando los veo errantes,
buscando reposo y no hallando ninguno excepto el que está contaminado,
de modo que sus almas languidecen por falta de la
abundancia de la casa de Dios y del disfrute de ella.
Mi alma le ruega a Él día y noche, para que los visite con Su brazo extendido.
Regresen, regresen a esa luz que les mostrará todo cuánto han hecho,
y los llevará a la casa del Padre donde su pan es seguro.
No gasten más dinero,
tiempo precioso o esfuerzo en aquello que solo es profesar o hablar del pan,
y que no puede satisfacer verdaderamente sus almas.

Por lo tanto, cada uno retírese a su interior, a sentir el poder glorioso, precioso,
antiguo, vivo y grande de Dios,
y permanezca en él y esté sujeto a él. Que todos atiendan diligentemente Sus enseñanzas,
directrices, revelaciones y operaciones, para que por Su luz todos los corazones,
familias y congregaciones sean examinados;
y para que todo lo que apague Su Espíritu Santo,
y sea ofensivo ante el ojo puro del Señor, sea descubierto,
y cada jardín sea inspeccionado, de tal modo que se vea qué es lo que crece allí,
para que así toda planta que el Señor no haya plantado sea descubierta y arrancada.
Porque el Señor se está levantando para probar, para aventar,
para purificar y para refinar.
El día viene y será ardiente como un horno; y ¿quién podrá soportar?
¿quién podrá estar en pie?
Esta es la pregunta que deben hacerse; porque el plomo, el estaño, sí,
y también "`la plata desechada,`"^
footnote:[Jeremías 6:30]
se desvanecerán en este fuego consumidor.
Y aquello que tenga la apariencia de oro,
pero que no sea de una naturaleza pura y duradera, será desecho,
y dejará pobre y vacío a todo a aquel que no posea el verdadero oro.

Por lo tanto, queridos amigos de todas partes, les digo, en el temor,
reverencia y nombre del Señor, apresúrense,
apresúrense a salir de todo lo que no tenga sustancia,
de esa naturaleza que mantiene el alma en todo tipo
de esclavitud y distancia del Señor. Sí,
apresúrense a salir del estado que profesa la verdad
en una naturaleza y espíritu contrarios a ella,
lo cual apaga al Espíritu del Señor Dios.
Queridos amigos, el ojo puro del Señor que recorre toda la tierra,
mirando a los malos y a los buenos, ve todos los estados y condiciones,
todos los caminos y nacimientos falsos.
Él ve a todos los que huyen de la cruz diaria,
los que han perdido la dulce y preciosa imagen de Dios,
y están creciendo en otra imagen en la casa de imágenes.
Él ve a todos los que se apartan de la sabiduría que es dulce, enternecedora y celestial,
a aquella que es terrenal y sensual,
en la cual hay un orgullo de las experiencias pasadas,
un tipo de conocimiento que produce dolor,
y donde continuamente se engorda y se fortalece en eso que debe ser alimentado con juicio.
Yo digo, el ojo puro e inmortal del Dios eterno ve todos estos estados y condiciones,
y todos los atajos y caminos torcidos a los cuales conduce el enemigo de las almas.

Por lo tanto, apresúrense,
apresúrense a encontrar al Señor Dios Todopoderoso en el camino de Sus juicios.
Humíllense, humíllense ante el poder puro del Señor;
siéntanlo ardiendo y consumiendo en donde sea que haya algo que hiera al alma,
que la lleve a la esclavitud y que oscurezca el entendimiento.
Dejen que todo sea sometido bajo el dominio y reino de este glorioso poder,
mediante su obra que consume,
destruye y quema completamente todo lo que es contrario a la naturaleza divina.
En este poder inmortal, se experimenta la paz con el Señor,
por medio de Su bendita obra de matar espiritualmente al enemigo;
y de este modo se obtiene la reconciliación con Dios mediante Jesucristo nuestro Señor.

Y todos los que son amantes de este dulce y antiguo poder del Señor,
quienes han tenido toques celestiales de él,
y revelaciones preciosas y dulces por medio de él, ¡oh moren con él y en él,
y él les dará el deseo de sus almas, coronándolos con dominio sobre el hombre de pecado,
tanto en la raíz como en el fruto!
Y en este poder su hombre interior caminará en el espíritu con Dios quien es Espíritu,
y ustedes obtendrán eso que Enoc obtuvo, es decir, el testimonio de que agradan a Dios.^
footnote:[Hebreos 11:5]
Y por lo tanto, a todos los amigos en todo lugar, les digo,
esperen por el brote fresco y el levantamiento glorioso
de este omnipotente poder del Señor,
para que él se manifieste a sí mismo en todas partes, rasgando todo velo,
quebrando toda cadena, abriendo todo sepulcro, resucitando toda alma a la vida eterna.
Entonces, en todas sus congregaciones y reuniones en todo lugar, tendrán este testimonio:
que "`la vida y la inmortalidad han sido sacadas a luz,`"^
footnote:[2 Timoteo 1:10]
y en ello se alegrarán con gozo inefable y glorioso,
porque este poder inmortal reina sobre todo, resplandece sobre todo, riega todo,
derrite todo, llena todo y endulza todo.
Y en el disfrute de su llenura espiritual, se levantarán santas alabanzas,
y acciones de gracias (en la melodía dulce y espiritual de la vida
eterna) brotarán y serán ofrecidas en el dulce sentido de Su amor,
el cual es el gran poder de Dios para salvación. Y así todo lo que es falso y erróneo,
todo lo que apaga el buen Espíritu del Señor,
será arrastrado y expulsado por el poderoso torrente del poder
inmortal de Aquel que es la Fuente de todos los seres.

Pero, a todos los que han perdido su camino,
les hago sonar la trompeta del Señor en sus oídos: Prepárense, prepárense,
para encontrarse con Jehová el Señor "`en el valle de la decisión.`"^
footnote:[Joel 3:14]
Y a todos los que tienen alguna ternura en sus corazones, y suspiros en pos del Señor,
esparcidos entre todas las denominaciones cristianas, les digo: Salgan,
salgan de Babilonia, y apártense; no toquen lo inmundo, para que el Señor los reciba.
Porque Él está listo para recibir a todos los que vengan a Él en Verdad y justicia,
y les pondrá una señal en la frente a todos los que
lloran por causa de los pecados del pueblo,
los cuales son grandes.
Por lo tanto, huyan por sus vidas fuera de la naturaleza de Sodoma,
y no se estanquen en una simple profesión de palabras que no provenga de la obra
inmediata de Dios y de la operación diaria de Su poder eterno en sus corazones.
Más bien,
desciendan a la obediencia a la voz pura y quieta del Espíritu (el don
de Dios en sus propios corazones) que los dirigirá (a medida que su oído
interior esté atento) en el camino estrecho de la vida eterna.
Aquí ustedes llegarán a aquello que inclinó sus corazones hacia Dios muchos años atrás,
y produjo en ustedes la ternura de espíritu.
Ahora, caminen en eso y sean fieles,
y los llevará a la Fuente de bendición de la cual vino, y al poderío del Ungido de Dios;
y así miles de personas de todas las naciones,
lenguas y pueblos se congregarán a Aquel que se llama "`Siloh;`"^
footnote:[Génesis 49:10, es decir, el Mesías]
y el monte de la casa del Señor será exaltado sobre todos los montes,
en medio de este gran día de prueba, tribulación y angustia.

Que el Señor Dios Todopoderoso alcance todos los
corazones que tengan algún deseo ferviente por Él,
esparcidos entre todas las denominaciones religiosas,
y atraiga a muchos a Sí mismo como tizones arrebatados del incendio.
Este es el anhelo de mi alma,
quien sufre dolores de parto por la visitación y
redención universal de la semilla de Jacob.

[.signed-section-signature]
Charles Marshall
